server:
  port: 8081

spring:
  application:
    name: user-service # 이 모듈의 애플리케이션 이름
  profiles:
    active: local  # 기본 활성화할 프로파일 (local). 운영환경에서는 환경변수나 실행 시 덮어써야 함

  jackson:
    serialization:
      indent-output: true # JSON 응답을 가독성 있게 출력

  jpa:
    open-in-view: false  # OSIV(Open Session In View) 비활성화로 트랜잭션 경계 명확히
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # 공통 DB Dialect. 실제 DB에 따라 local/prod에서 override 가능

logging:
  level:
    root: info  # 전체 로그 레벨
    app.ledger: debug  # 본인의 패키지 루트에 맞게 지정하면 상세 로그 확인 가능
