name: CI - Build and Test # WorkFlow 이름

on: # 트리거 설정
  push: # Push가 발생 하였을 때
    branches: [ "main" ] # main 브랜치에
  pull_request: # Pull Request가 발생 하였을 때
    branches: [ "main" ] #main 브랜치에

jobs: # 작업 단위
  build: # 작업단위 이름
    runs-on: ubuntu-latest # github가 제공하는 가상머신 이름

    steps: # job의 단계별 이름
    - name: Checkout source # GitHub repo 코드를 체크아웃하는 단계 이름
      uses: actions/checkout@v4 # actions/checkout@v4 액션을 사용해 코드를 내려받음

    - name: Set up JDK # JDK 설정 단계의 이름
      uses: actions/setup-java@v4 # setup-java 액션을 사용해 JDK 설치
      with: # 	어떤 배포판과 어떤 버전의 Java를 쓸 것인지 설정
        distribution: 'temurin'
        java-version: '21'  # 또는 프로젝트에 맞는 버전

    - name: Grant execute permission to Gradle
      run: chmod +x ./gradlew # gradlew 실행 권한 부여 (Unix 환경에서 필수)

    - name: Build with Gradle
      run: ./gradlew build # Gradle 빌드 명령 실행 (build, test, jar 포함됨)

  # 추후 다음 기능 확장 고려
  # Docker 빌드 - docker build, docker push와 연동
  # EC2/S3 배포 - AWS CLI, scp, CodeDeploy 등과 연동
  # 슬랙 / 디스코드 알림 - workflow에 Webhook 추가